# Generated by Django 4.1.7 on 2023-03-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etymology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('example', models.TextField(max_length=250)),
                ('verbiage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.verbiage')),
            ],
        ),
    ]
