# Generated by Django 4.1.7 on 2023-03-07 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_etymology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etymology',
            old_name='year',
            new_name='date',
        ),
    ]
